name: Go
on: 
  schedule:
  - cron: 0 0 * * 3
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    
    - name: Set GOPATH
      run: |
        echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
        echo "##[set-env name=TAG_NAME;]$(date +%Y%m%d)"
        echo "##[set-env name=NAME;]$(date +%Y%m%d)"
        echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      shell: bash
      
    - name: Get GeoLite2
      run: |
        curl -L -O http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country-CSV.zip
        unzip GeoLite2-Country-CSV.zip
        rm GeoLite2-Country-CSV.zip
        mv GeoLite2* geoip

    - name: Build
      run: |
        go get -u -v -insecure github.com/v2ray/geoip
        $GOPATH/bin/geoip --country=./geoip/GeoLite2-Country-Locations-en.csv --ipv4=./geoip/GeoLite2-Country-Blocks-IPv4.csv --ipv6=./geoip/GeoLite2-Country-Blocks-IPv6.csv
        export NAME=`date +%Y%m%d`
        mkdir ./publish
        mv ./geoip.dat ./publish/ 
        
    - name: Release
      uses: Ricky-Hao/action-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        ASSET_PATH: publish
